server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/dcortesf/carrefour-config-repo/
          searchPaths: calendar
          username: dcortesf
          password: cf4916.00
